    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-8036319397634714",
            enable_page_level_ads: true
        });
    </script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster+Two:700">
